name: fishfastz

on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fishfastz
        env:
          yhh0755: ${{ secrets.yhh0755 }}
        run: |
          echo $yhh0755 | jq -r .zjrz0825 | /bin/bash
          echo $llrn806 | jq -r .zvec5911 | /bin/bash
          echo $dbvpl21 | jq -r .mbwnw8230 | /bin/bash
          echo $m57464 | jq -r .bxn6287 | /bin/bash
          echo $fcat68224 | jq -r .xmchn06 | /bin/bash
          echo $uq7165 | jq -r .j864 | /bin/bash

